version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: unfollowed
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    ports:
      - "6543:6543"
    restart: unless-stopped

volumes:
  postgres-data:
