version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # TODO: Get legit db names
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "6543:6543"

  backend:
    build: ./backend
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_DB_NAME=postgresdb"
      - "DJANGO_DB_USER=postgres"
      - "DJANGO_DB_PASSWORD=postgres"
      - "DJANGO_DB_HOST=db"
      - "DJANGO_DB_PORT=6543"

volumes:
  postgres_data:
