# Generated by Django 5.0.1 on 2024-03-31 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('insta_name', models.CharField(blank=True, max_length=100, null=True)),
                ('followers', models.JSONField(blank=True, default=list)),
                ('following', models.JSONField(blank=True, default=list)),
                ('fans', models.JSONField(blank=True, default=list)),
                ('unfollowers', models.JSONField(blank=True, default=list)),
                ('isProcessed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.JSONField()),
                ('action', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
    ]
