# Generated by Django 5.0.1 on 2024-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("insta_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fans",
                    models.ManyToManyField(
                        blank=True, related_name="user_fans", to="server.user"
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True, related_name="user_followers", to="server.user"
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="user_following", to="server.user"
                    ),
                ),
                (
                    "unfollowers",
                    models.ManyToManyField(
                        blank=True, related_name="user_unfollowers", to="server.user"
                    ),
                ),
            ],
        ),
    ]
