# Generated by Django 5.0.1 on 2024-03-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_user_isprocessed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fans",
        ),
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.RemoveField(
            model_name="user",
            name="unfollowers",
        ),
        migrations.AddField(
            model_name="user",
            name="fans",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="unfollowers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
