# Generated by Django 5.0.1 on 2024-04-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
