# Generated by Django 5.0.1 on 2024-09-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0011_auto_20240905_0336"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="recent_follows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="recent_unfollows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="unfollows",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
