# Generated by Django 5.0.1 on 2024-09-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_user_follows_user_recent_follows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
